import pandas as pd
from os import environ
from openai import OpenAI
import json

from openai.resources.beta.chat import Completions

############# Basic Setting ##################
PIlevel = [95]  # 95,75,50,25,5
mu, rho, sigma = 30.0, 0.6, 3.0
num_predictions = 1
informDGP = [True]  # [True, False]
CompletionsRESULT = []

JSON_SCHEMA = {
    "name": "forecast_result",
    "schema": {
        "type": "object",
        "properties": {
            "mean": {
                "type": "number" #整数的话用 “integer”
            },
            "lower_bound": {
                "type":  "number"
            },
            "upper_bound": {
                "type":  "number"
            }
        },
        "required": ["mean", "lower_bound", "upper_bound"],
        "additionalProperties": False
    },
    "strict": True
}
##############################################

client = OpenAI(api_key=environ.get('OPENAI_API_KEY'))

MODEL = "gpt-4o"
TEMP = 1



for level in PIlevel:
    for inform in informDGP:
        SystemPROMPT = (
                "You are forecasting a univariate time series"
                + (
                    f"The data-generating process (DGP) is generated from an AR(1) process:\n"
                    f"  x_t = {mu} + {rho} * (x_(t-1) - {mu}) + ε_t,\n"
                    f"where ε_t are i.i.d. normal shocks with mean 0 and standard deviation {sigma}, "
                    f"i.e., ε_t ~ N(0, {sigma}^2). "
                    if inform else
                    "The DGP parameters are not disclosed to you. "
                )
                +
                "Your task: Given the observed history, forecast x_{t+1} and construct a prediction interval.\n"
                "\n"
                "INTERVAL DEFINITION:\n"
                "When the user requests an X% prediction interval (e.g., 95%), ALWAYS interpret it strictly as:\n"
                "  “The future true value x_{t+1} has X% probability of falling inside this interval.”\n"
                "This is the CENTRAL X% PREDICTION INTERVAL, constructed by trimming equal probability from both tails.\n"
                "\n"
                "Mathematically:\n"
                "  p_low  = (1 - X/100) / 2\n"
                "  p_high = 1 - p_low\n"
                "  lower_bound = Quantile[p_low]  of your predictive distribution for x_{t+1}\n"
                "  upper_bound = Quantile[p_high] of your predictive distribution for x_{t+1}\n"
                "OUTPUT FORMAT:\n"
                ##### important but not very important
                "Respond ONLY in valid JSON with the keys:\n"
                "  'mean', 'lower_bound', 'upper_bound'\n"
                "Ensure: lower_bound ≤ upper_bound.\n"
        )

        csv_path = "dgp_01.csv"
        df = pd.read_csv(csv_path)
        x_data = df[df['Period'] <= 40]['x_t'].tolist()

        UserPROMPT = f"""
                        Here are the most recent 40 observations of a univariate time series (ordered from t=1 to t=40):
                        {x_data}

                        {f'The series is generated by the AR(1) process: x_t = {mu} + {rho}*(x_(t-1)-{mu}) + ε_t, with ε_t ~ N(0,{sigma}^2).' if inform else ''}

                        Your tasks are:

                        1) Produce a point forecast for x_41 (use key 'mean').

                        2) Construct the CENTRAL {level}% prediction interval for x_41.
                           The interval must satisfy:
                              p_low  = (1 - {level}/100) / 2
                              p_high = 1 - p_low
                           where:
                              lower_bound = Quantile(p_low)  of your predictive distribution for x_41
                              upper_bound = Quantile(p_high) of your predictive distribution for x_41

                           This is a PREDICTION INTERVAL: the true future value x_41 must have {level}% probability of falling inside it.
                """
        all_results = []
        # 多次预测
        for pred_num in range(1, num_predictions + 1):

            completion = client.chat.completions.create(
                model=MODEL,
                messages=[
                    {"role": "system", "content": SystemPROMPT},
                    {"role": "user", "content": UserPROMPT}
                ],
                temperature=TEMP,
                # response_format = { "type": "json_object" } # json_mode

                # Setting to { "type": "json_schema", "json_schema": {...} }
                # enables Structured Outputs which ensures the model will match your supplied JSON schema.
                response_format = { "type": "json_schema", "json_schema": JSON_SCHEMA }
            )

            print("\ncompletion:", completion)
            print("\ntype of completion:", type(completion))
            print("\n")


            # 获取响应内容
            ChatAPI_content = completion.choices[0].message.content

            # 获取响应内容
            print("ChatAPI_content:", ChatAPI_content)
            print("type of ChatAPI_content:", type(ChatAPI_content))

            results = json.loads(ChatAPI_content)
            print("results:", results)
            print("type of results:", type(results))

            #存醋
            results["prediction_round"] = pred_num
            all_results.append(results)


        # 创建结果DataFrame
        results_df = pd.DataFrame(all_results)

        output_path = 'output2.csv' if inform else 'noDGP2.csv'
        results_df.to_csv(output_path, index=False)

