import pandas as pd
from os import environ
from openai import OpenAI
from pydantic import BaseModel


############# Basic Setting ##################
PIlevel = [95]  # 95,75,50,25,5
mu, rho, sigma = 30.0, 0.6, 3.0
num_predictions = 1
informDGP = [True] #[True, False]
##############################################

client = OpenAI(api_key=environ.get('OPENAI_API_KEY'))

MODEL = "gpt-4o"
TEMP = 1

class Prediction(BaseModel):
    mean: float
    lower_bound: float
    upper_bound: float

for level in PIlevel:
    for inform in informDGP:
        SystemPROMPT = (
                "You are forecasting a univariate time series"
                + (
                    f"The data-generating process (DGP) is generated from an AR(1) process:\n"
                    f"  x_t = {mu} + {rho} * (x_(t-1) - {mu}) + ε_t,\n"
                    f"where ε_t are i.i.d. normal shocks with mean 0 and standard deviation {sigma}, "
                    f"i.e., ε_t ~ N(0, {sigma}^2). "
                    if inform else
                    "The DGP parameters are not disclosed to you. "
                )
                +
                "Your task: Given the observed history, forecast x_{t+1} and construct a prediction interval.\n"
                "\n"
                "INTERVAL DEFINITION:\n"
                "When the user requests an X% prediction interval (e.g., 95%), ALWAYS interpret it strictly as:\n"
                " “The future true value x_{t+1} has X% probability of falling inside this interval.”\n"
                "Output the point forecast, the lower_bound and the upper_bound of the forecast\n"
        )

        csv_path = "dgp_01.csv"
        df = pd.read_csv(csv_path)
        x_data = df[df['Period'] <= 40]['x_t'].tolist()

        UserPROMPT = f"""
                        Here are the most recent 40 observations of a univariate time series (ordered from t=1 to t=40):
                        {x_data}
                
                        {f'The series is generated by the AR(1) process: x_t = {mu} + {rho}*(x_(t-1)-{mu}) + ε_t, with ε_t ~ N(0,{sigma}^2).' if inform else ''}
                
                        Your tasks are:
                
                        1) Produce a point forecast for x_41 (use key 'mean').
                
                        2) Construct the CENTRAL {level}% prediction interval for x_41.
                           The interval must satisfy:
                              p_low  = (1 - {level}/100) / 2
                              p_high = 1 - p_low
                           where:
                              lower_bound = Quantile(p_low)  of your predictive distribution for x_41
                              upper_bound = Quantile(p_high) of your predictive distribution for x_41
                
                           This is a PREDICTION INTERVAL: the true future value x_41 must have {level}% probability of falling inside it.
                """

        all_results = []
        #多次预测
        for pred_num in range(1, num_predictions + 1):
                completion = client.responses.parse(
                    model=MODEL,
                    input=[
                        {"role": "system",
                         "content": SystemPROMPT},
                        {"role": "user",
                         "content": UserPROMPT}
                    ],
                    temperature=TEMP,
                    text_format=Prediction,
                )

                # 获取响应内容
                print("completion: ", completion)
                print(completion.output_text)
                print(type(completion.output_text))

                response_content = completion.output_parsed
                print("prediction: ", response_content)


                prediction = completion.output_parsed  # 类型：Prediction
                mean = prediction.mean
                print("\nmean: ", mean)

                record = prediction.model_dump()       # 用model_dump() 方法将class转换成dict
                record["prediction_round"] = pred_num  # 加一个额外字段
                all_results.append(record)


        # 创建结果DataFrame
        results_df = pd.DataFrame(all_results)

        output_path = 'output.csv' if inform else 'noDGP.csv'
        results_df.to_csv(output_path, index=False)
