SystemPROMPT_T1firstnofine = (
    "経済学実験における参加者間のチャットログを送信します。この実験は、2人（プレイヤー1とプレイヤー2）を1組とした「第一価格オークション（first price auction）」形式で行われます。両参加者は、自分だけが確認できる商品の「評価額（value）」を持っています。"
    "入札前に両者はチャットでコミュニケートすることが可能です。入札後、最も高い価格（bid）を提示した者が勝者となり商品を受け取ります。勝者の利得（payoff）は「評価額 - 入札額（bid）」となります。また、勝者は自分の利得の一部を敗者に譲渡（transfer）することも選択できます。"
    "提供するチャットログを分析し、以下の情報を抽出してください："
    "- プレイヤー1が自身の評価額（具体的な数値）を伝えたか：player1_whether_inform_exact_self_value"
    "- プレイヤー2が自身の評価額（具体的な数値）を伝えたか：player2_whether_inform_exact_self_value"
    "- プレイヤー1が自身の評価額の範囲（インターバル）を伝えたか：player1_whether_inform_value_interval"
    "- プレイヤー2が自身の評価額の範囲（インターバル）を伝えたか：player2_whether_inform_value_interval"
    "- プレイヤー1が評価額を伝えた場合、その数値はいくらか（ない場合は-1）：player1_inform_exact_self_value"
    "- プレイヤー 2が評価額を伝えた場合、その数値はいくらか（ない場合は-1）：player2_inform_exact_self_value"
    "- プレイヤー 1が評価額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player1_inform_value_interval_minbound, player1_inform_value_interval_maxbound"
    "- プレイヤー 2が評価額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player2_inform_value_interval_minbound, player2_inform_value_interval_maxbound"
    "- プレイヤー 1が自身の入札額（bid：具体的な数値）を相手に伝えたか：player1_whether_inform_exact_self_bid"
    "- プレイヤー 2が自身の入札額（bid：具体的な数値）を相手に伝えたか：player2_whether_inform_exact_self_bid"
    "- プレイヤー 1が自身の入札額の範囲を伝えたか：player1_whether_inform_bid_interval"
    "- プレイヤー 2が自身の入札額の範囲を伝えたか：player2_whether_inform_bid_interval"
    "- プレイヤー 1が入札額を伝えた場合、その数値はいくらか（ない場合は-1）：player1_inform_exact_self_bid"
    "- プレイヤー 2が入札額を伝えた場合, その数値はいくらか（ない場合は-1）：player2_inform_exact_self_bid"
    "- 注意：ここでの「bid」は入札価格であり、利得（payoff）ではありません。"
    "- プレイヤー 1が入札額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player1_inform_bid_interval_minbound, player1_inform_bid_interval_maxbound"
    "- プレイヤー 2が入札額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player2_inform_bid_interval_minbound, player2_inform_bid_interval_maxbound"
    "- 両者が事前に勝者を決定したか（決定していない場合は-1、どちらでも良いと決めた場合は0、プレイヤー1と決めた場合は1、プレイヤー2と決めた場合は2）：Whether_Pre_Decide_Winner"
    "- 事前に勝者を決めた際、勝者から敗者への送金（transfer）形式を以下から選択：'50% of the payoff' / 'Exact number' / 'Interval' / 'Some points (not specific)' / 'Nothing(not mentioned or no pre-decided winner)': Pre_Decide_Winner_Committed_Transfer_Format"
    "- 約束された送金の具体的な数値はいくらか（ない場合は-1）：Pre_Decide_Winner_Committed_Transfer_Number"
    "- 約束された送金額の範囲（下限と上限）はいくらか（ない場合は-1）：Pre_Decide_Winner_Committed_Transfer_interval_minbound, Pre_Decide_Winner_Committed_Transfer_interval_maxbound"
    "- 談合（共謀・Collusion）の疑いがあるか判断してください（例：事前に勝者を決める、「共謀に誓います」「協力します」といった談合を示唆する発言があるなど）。（ない場合は-1、不明な場合は0、ある場合は1）：Whether_Collusion"
)

SystemPROMPT_T2firstfine0 = (
    "経済学実験における参加者間のチャットログを送信します。この実験は、2人（プレイヤー1とプレイヤー2）を1組とした「第一価格オークション（first price auction）」形式で行われます。両参加者は、自分だけが確認できる商品の「評価額（value）」を持っています。"
    "入札前に両者はチャットでコミュニケートすることが可能です。入札後、最も高い価格（bid）を提示した者が勝者となり商品を受け取ります。勝者の利得（payoff）は「評価額 - 入札額（bid）」となります。また、勝者は自分の利得の一部を敗者に譲渡（transfer）することも選択できます。"

    ###############################################################################################################################################################################################################
    "ただし、事前にチャットでコミュニケートするしたり、譲渡（transfer）を行ったりした場合、談合を締結したものとみなされ、両者に罰金が科される可能性があります。罰金額は250ポイントですが、今回の談合の検知確率は0％に設定されています。"
    "検知される確率は0%であるため、実際に罰金が発生する確率は0%です"
    ######################################################################################################################################################################################

    "提供するチャットログを分析し、以下の情報を抽出してください："
    "- プレイヤー1が自身の評価額（具体的な数値）を伝えたか：player1_whether_inform_exact_self_value"
    "- プレイヤー2が自身の評価額（具体的な数値）を伝えたか：player2_whether_inform_exact_self_value"
    "- プレイヤー1が自身の評価額の範囲（インターバル）を伝えたか：player1_whether_inform_value_interval"
    "- プレイヤー2が自身の評価額の範囲（インターバル）を伝えたか：player2_whether_inform_value_interval"
    "- プレイヤー1が評価額を伝えた場合、その数値はいくらか（ない場合は-1）：player1_inform_exact_self_value"
    "- プレイヤー 2が評価額を伝えた場合、その数値はいくらか（ない場合は-1）：player2_inform_exact_self_value"
    "- プレイヤー 1が評価額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player1_inform_value_interval_minbound, player1_inform_value_interval_maxbound"
    "- プレイヤー 2が評価額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player2_inform_value_interval_minbound, player2_inform_value_interval_maxbound"
    "- プレイヤー 1が自身の入札額（bid：具体的な数値）を相手に伝えたか：player1_whether_inform_exact_self_bid"
    "- プレイヤー 2が自身の入札額（bid：具体的な数値）を相手に伝えたか：player2_whether_inform_exact_self_bid"
    "- プレイヤー 1が自身の入札額の範囲を伝えたか：player1_whether_inform_bid_interval"
    "- プレイヤー 2が自身の入札額の範囲を伝えたか：player2_whether_inform_bid_interval"
    "- プレイヤー 1が入札額を伝えた場合、その数値はいくらか（ない場合は-1）：player1_inform_exact_self_bid"
    "- プレイヤー 2が入札額を伝えた場合, その数値はいくらか（ない場合は-1）：player2_inform_exact_self_bid"
    "- 注意：ここでの「bid」は入札価格であり、利得（payoff）ではありません。"
    "- プレイヤー 1が入札額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player1_inform_bid_interval_minbound, player1_inform_bid_interval_maxbound"
    "- プレイヤー 2が入札額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player2_inform_bid_interval_minbound, player2_inform_bid_interval_maxbound"
    "- 両者が事前に勝者を決定したか（決定していない場合は-1、どちらでも良いと決めた場合は0、プレイヤー1と決めた場合は1、プレイヤー2と決めた場合は2）：Whether_Pre_Decide_Winner"
    "- 事前に勝者を決めた際、勝者から敗者への送金（transfer）形式を以下から選択：'50% of the payoff' / 'Exact number' / 'Interval' / 'Some points (not specific)' / 'Nothing(not mentioned or no pre-decided winner)': Pre_Decide_Winner_Committed_Transfer_Format"
    "- 約束された送金の具体的な数値はいくらか（ない場合は-1）：Pre_Decide_Winner_Committed_Transfer_Number"
    "- 約束された送金額の範囲（下限と上限）はいくらか（ない場合は-1）：Pre_Decide_Winner_Committed_Transfer_interval_minbound, Pre_Decide_Winner_Committed_Transfer_interval_maxbound"
    "- 談合（共謀・Collusion）の疑いがあるか判断してください（例：事前に勝者を決める、「共謀に誓います」「協力します」といった談合を示唆する発言があるなど）。（ない場合は-1、不明な場合は0、ある場合は1）：Whether_Collusion"
)

SystemPROMPT_T3firstfine25 = (
    "経済学実験における参加者間のチャットログを送信します。この実験は、2人（プレイヤー1とプレイヤー2）を1組とした「第一価格オークション（first price auction）」形式で行われます。両参加者は、自分だけが確認できる商品の「評価額（value）」を持っています。"
    "入札前に両者はチャットでコミュニケートすることが可能です。入札後、最も高い価格（bid）を提示した者が勝者となり商品を受け取ります。勝者の利得（payoff）は「評価額 - 入札額（bid）」となります。また、勝者は自分の利得の一部を敗者に譲渡（transfer）することも選択できます。"

    ###############################################################################################################################################################################################################
    "【罰金ルール】事前にチャットで交流したり譲渡（transfer）を行ったりした場合、談合（Collusion）とみなされ、両者に250ポイントの罰金が科される可能性があります。今回の談合検知確率は25％です。"
    "- 談合が検知されなかった場合（確率75％）：罰金を支払う必要はありません。"
    "- 談合が検知された場合（確率25％）：罰金250ポイントを支払う必要があります。"
    ######################################################################################################################################################################################

    "提供するチャットログを分析し、以下の情報を抽出してください："
    "- プレイヤー1が自身の評価額（具体的な数値）を伝えたか：player1_whether_inform_exact_self_value"
    "- プレイヤー2が自身の評価額（具体的な数値）を伝えたか：player2_whether_inform_exact_self_value"
    "- プレイヤー1が自身の評価額の範囲（インターバル）を伝えたか：player1_whether_inform_value_interval"
    "- プレイヤー2が自身の評価額の範囲（インターバル）を伝えたか：player2_whether_inform_value_interval"
    "- プレイヤー1が評価額を伝えた場合、その数値はいくらか（ない場合は-1）：player1_inform_exact_self_value"
    "- プレイヤー 2が評価額を伝えた場合、その数値はいくらか（ない場合は-1）：player2_inform_exact_self_value"
    "- プレイヤー 1が評価額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player1_inform_value_interval_minbound, player1_inform_value_interval_maxbound"
    "- プレイヤー 2が評価額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player2_inform_value_interval_minbound, player2_inform_value_interval_maxbound"
    "- プレイヤー 1が自身の入札額（bid：具体的な数値）を相手に伝えたか：player1_whether_inform_exact_self_bid"
    "- プレイヤー 2が自身の入札額（bid：具体的な数値）を相手に伝えたか：player2_whether_inform_exact_self_bid"
    "- プレイヤー 1が自身の入札額の範囲を伝えたか：player1_whether_inform_bid_interval"
    "- プレイヤー 2が自身の入札額の範囲を伝えたか：player2_whether_inform_bid_interval"
    "- プレイヤー 1が入札額を伝えた場合、その数値はいくらか（ない場合は-1）：player1_inform_exact_self_bid"
    "- プレイヤー 2が入札額を伝えた場合, その数値はいくらか（ない場合は-1）：player2_inform_exact_self_bid"
    "- 注意：ここでの「bid」は入札価格であり、利得（payoff）ではありません。"
    "- プレイヤー 1が入札額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player1_inform_bid_interval_minbound, player1_inform_bid_interval_maxbound"
    "- プレイヤー 2が入札額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player2_inform_bid_interval_minbound, player2_inform_bid_interval_maxbound"
    "- 両者が事前に勝者を決定したか（決定していない場合は-1、どちらでも良いと決めた場合は0、プレイヤー1と決めた場合は1、プレイヤー2と決めた場合は2）：Whether_Pre_Decide_Winner"
    "- 事前に勝者を決めた際、勝者から敗者への送金（transfer）形式を以下から選択：'50% of the payoff' / 'Exact number' / 'Interval' / 'Some points (not specific)' / 'Nothing(not mentioned or no pre-decided winner)': Pre_Decide_Winner_Committed_Transfer_Format"
    "- 約束された送金の具体的な数値はいくらか（ない場合は-1）：Pre_Decide_Winner_Committed_Transfer_Number"
    "- 約束された送金額の範囲（下限と上限）はいくらか（ない場合は-1）：Pre_Decide_Winner_Committed_Transfer_interval_minbound, Pre_Decide_Winner_Committed_Transfer_interval_maxbound"
    "- 談合（共謀・Collusion）の疑いがあるか判断してください（例：事前に勝者を決める、「共謀に誓います」「協力します」といった談合を示唆する発言があるなど）。（ない場合は-1、不明な場合は0、ある場合は1）：Whether_Collusion"
)


##############################################################################################################################################################################################################################################

SystemPROMPT_T4secondnofine = (
    "経済学実験における参加者間のチャットログを送信します。この実験は、2人（プレイヤー1とプレイヤー2）を1組とした「第二価格オークション（second price auction）」形式で行われます。両参加者は、自分だけが確認できる商品の「評価額（value）」を持っています。"
    "入札前に両者はチャットでコミュニケートすることが可能です。入札後、最も高い価格（bid）を提示した者が勝者となり商品を受け取ります。勝者の利得（payoff）は「評価額 - 2番目に高い入札額（敗者のbid）」となります。また、勝者は自分の利得の一部を敗者に譲渡（transfer）することも選択できます。"
    "提供するチャットログを分析し、以下の情報を抽出してください："
    "- プレイヤー1が自身の評価額（具体的な数値）を伝えたか：player1_whether_inform_exact_self_value"
    "- プレイヤー2が自身の評価額（具体的な数値）を伝えたか：player2_whether_inform_exact_self_value"
    "- プレイヤー1が自身の評価額の範囲（インターバル）を伝えたか：player1_whether_inform_value_interval"
    "- プレイヤー2が自身の評価額の範囲（インターバル）を伝えたか：player2_whether_inform_value_interval"
    "- プレイヤー1が評価額を伝えた場合、その数値はいくらか（ない場合は-1）：player1_inform_exact_self_value"
    "- プレイヤー 2が評価額を伝えた場合、その数値はいくらか（ない場合は-1）：player2_inform_exact_self_value"
    "- プレイヤー 1が評価額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player1_inform_value_interval_minbound, player1_inform_value_interval_maxbound"
    "- プレイヤー 2が評価額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player2_inform_value_interval_minbound, player2_inform_value_interval_maxbound"
    "- プレイヤー 1が自身の入札額（bid：具体的な数値）を相手に伝えたか：player1_whether_inform_exact_self_bid"
    "- プレイヤー 2が自身の入札額（bid：具体的な数値）を相手に伝えたか：player2_whether_inform_exact_self_bid"
    "- プレイヤー 1が自身の入札額の範囲を伝えたか：player1_whether_inform_bid_interval"
    "- プレイヤー 2が自身の入札額の範囲を伝えたか：player2_whether_inform_bid_interval"
    "- プレイヤー 1が入札額を伝えた場合、その数値はいくらか（ない場合は-1）：player1_inform_exact_self_bid"
    "- プレイヤー 2が入札額を伝えた場合, その数値はいくらか（ない場合は-1）：player2_inform_exact_self_bid"
    "- 注意：ここでの「bid」は入札価格であり、利得（payoff）ではありません。"
    "- プレイヤー 1が入札額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player1_inform_bid_interval_minbound, player1_inform_bid_interval_maxbound"
    "- プレイヤー 2が入札額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player2_inform_bid_interval_minbound, player2_inform_bid_interval_maxbound"
    "- 両者が事前に勝者を決定したか（決定していない場合は-1、どちらでも良いと決めた場合は0、プレイヤー1と決めた場合は1、プレイヤー2と決めた場合は2）：Whether_Pre_Decide_Winner"
    "- 事前に勝者を決めた際、勝者から敗者への送金（transfer）形式を以下から選択：'50% of the payoff' / 'Exact number' / 'Interval' / 'Some points (not specific)' / 'Nothing(not mentioned or no pre-decided winner)': Pre_Decide_Winner_Committed_Transfer_Format"
    "- 約束された送金の具体的な数値はいくらか（ない場合は-1）：Pre_Decide_Winner_Committed_Transfer_Number"
    "- 約束された送金額の範囲（下限と上限）はいくらか（ない場合は-1）：Pre_Decide_Winner_Committed_Transfer_interval_minbound, Pre_Decide_Winner_Committed_Transfer_interval_maxbound"
    "- 談合（共謀・Collusion）の疑いがあるか判断してください（例：事前に勝者を決める、「共謀に誓います」「協力します」といった談合を示唆する発言があるなど）。（ない場合は-1、不明な場合は0、ある場合は1）：Whether_Collusion"
)

SystemPROMPT_T5secondfine0 = (
    "経済学実験における参加者間のチャットログを送信します。この実験は、2人（プレイヤー1とプレイヤー2）を1組とした「第二価格オークション（second price auction）」形式で行われます。両参加者は、自分だけが確認できる商品の「評価額（value）」を持っています。"
    "入札前に両者はチャットでコミュニケートすることが可能です。入札後、最も高い価格（bid）を提示した者が勝者となり商品を受け取ります。勝者の利得（payoff）は「評価額 - 2番目に高い入札額（敗者のbid）」となります。また、勝者は自分の利得の一部を敗者に譲渡（transfer）することも選択できます。"

    ###############################################################################################################################################################################################################
    "ただし、事前にチャットでコミュニケートするしたり、譲渡（transfer）を行ったりした場合、談合を締結したものとみなされ、両者に罰金が科される可能性があります。罰金額は250ポイントですが、今回の談合の検知確率は0％に設定されています。"
    "検知される確率は0%であるため、実際に罰金が発生する確率は0%です"
    ######################################################################################################################################################################################

    "提供するチャットログを分析し、以下の情報を抽出してください："
    "- プレイヤー1が自身の評価額（具体的な数値）を伝えたか：player1_whether_inform_exact_self_value"
    "- プレイヤー2が自身の評価額（具体的な数値）を伝えたか：player2_whether_inform_exact_self_value"
    "- プレイヤー1が自身の評価額の範囲（インターバル）を伝えたか：player1_whether_inform_value_interval"
    "- プレイヤー2が自身の評価額の範囲（インターバル）を伝えたか：player2_whether_inform_value_interval"
    "- プレイヤー1が評価額を伝えた場合、その数値はいくらか（ない場合は-1）：player1_inform_exact_self_value"
    "- プレイヤー 2が評価額を伝えた場合、その数値はいくらか（ない場合は-1）：player2_inform_exact_self_value"
    "- プレイヤー 1が評価額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player1_inform_value_interval_minbound, player1_inform_value_interval_maxbound"
    "- プレイヤー 2が評価額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player2_inform_value_interval_minbound, player2_inform_value_interval_maxbound"
    "- プレイヤー 1が自身の入札額（bid：具体的な数値）を相手に伝えたか：player1_whether_inform_exact_self_bid"
    "- プレイヤー 2が自身の入札額（bid：具体的な数値）を相手に伝えたか：player2_whether_inform_exact_self_bid"
    "- プレイヤー 1が自身の入札額の範囲を伝えたか：player1_whether_inform_bid_interval"
    "- プレイヤー 2が自身の入札額の範囲を伝えたか：player2_whether_inform_bid_interval"
    "- プレイヤー 1が入札額を伝えた場合、その数値はいくらか（ない場合は-1）：player1_inform_exact_self_bid"
    "- プレイヤー 2が入札額を伝えた場合, その数値はいくらか（ない場合は-1）：player2_inform_exact_self_bid"
    "- 注意：ここでの「bid」は入札価格であり、利得（payoff）ではありません。"
    "- プレイヤー 1が入札額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player1_inform_bid_interval_minbound, player1_inform_bid_interval_maxbound"
    "- プレイヤー 2が入札額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player2_inform_bid_interval_minbound, player2_inform_bid_interval_maxbound"
    "- 両者が事前に勝者を決定したか（決定していない場合は-1、どちらでも良いと決めた場合は0、プレイヤー1と決めた場合は1、プレイヤー2と決めた場合は2）：Whether_Pre_Decide_Winner"
    "- 事前に勝者を決めた際、勝者から敗者への送金（transfer）形式を以下から選択：'50% of the payoff' / 'Exact number' / 'Interval' / 'Some points (not specific)' / 'Nothing(not mentioned or no pre-decided winner)': Pre_Decide_Winner_Committed_Transfer_Format"
    "- 約束された送金の具体的な数値はいくらか（ない場合は-1）：Pre_Decide_Winner_Committed_Transfer_Number"
    "- 約束された送金額の範囲（下限と上限）はいくらか（ない場合は-1）：Pre_Decide_Winner_Committed_Transfer_interval_minbound, Pre_Decide_Winner_Committed_Transfer_interval_maxbound"
    "- 談合（共謀・Collusion）の疑いがあるか判断してください（例：事前に勝者を決める、「共謀に誓います」「協力します」といった談合を示唆する発言があるなど）。（ない場合は-1、不明な場合は0、ある場合は1）：Whether_Collusion"
)

SystemPROMPT_T6secondfine25 = (
    "経済学実験における参加者間のチャットログを送信します。この実験は、2人（プレイヤー1とプレイヤー2）を1組とした「第二価格オークション（second price auction）」形式で行われます。両参加者は、自分だけが確認できる商品の「評価額（value）」を持っています。"
    "入札前に両者はチャットでコミュニケートすることが可能です。入札後、最も高い価格（bid）を提示した者が勝者となり商品を受け取ります。勝者の利得（payoff）は「評価額 - 2番目に高い入札額（敗者のbid）」となります。また、勝者は自分の利得の一部を敗者に譲渡（transfer）することも選択できます。"

    ###############################################################################################################################################################################################################
    "【罰金ルール】事前にチャットで交流したり譲渡（transfer）を行ったりした場合、談合（Collusion）とみなされ、両者に250ポイントの罰金が科される可能性があります。今回の談合検知確率は25％です。"
    "- 談合が検知されなかった場合（確率75％）：罰金を支払う必要はありません。"
    "- 談合が検知された場合（確率25％）：罰金250ポイントを支払う必要があります。"
    ######################################################################################################################################################################################

    "提供するチャットログを分析し、以下の情報を抽出してください："
    "- プレイヤー1が自身の評価額（具体的な数値）を伝えたか：player1_whether_inform_exact_self_value"
    "- プレイヤー2が自身の評価額（具体的な数値）を伝えたか：player2_whether_inform_exact_self_value"
    "- プレイヤー1が自身の評価額の範囲（インターバル）を伝えたか：player1_whether_inform_value_interval"
    "- プレイヤー2が自身の評価額の範囲（インターバル）を伝えたか：player2_whether_inform_value_interval"
    "- プレイヤー1が評価額を伝えた場合、その数値はいくらか（ない場合は-1）：player1_inform_exact_self_value"
    "- プレイヤー 2が評価額を伝えた場合、その数値はいくらか（ない場合は-1）：player2_inform_exact_self_value"
    "- プレイヤー 1が評価額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player1_inform_value_interval_minbound, player1_inform_value_interval_maxbound"
    "- プレイヤー 2が評価額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player2_inform_value_interval_minbound, player2_inform_value_interval_maxbound"
    "- プレイヤー 1が自身の入札額（bid：具体的な数値）を相手に伝えたか：player1_whether_inform_exact_self_bid"
    "- プレイヤー 2が自身の入札額（bid：具体的な数値）を相手に伝えたか：player2_whether_inform_exact_self_bid"
    "- プレイヤー 1が自身の入札額の範囲を伝えたか：player1_whether_inform_bid_interval"
    "- プレイヤー 2が自身の入札額の範囲を伝えたか：player2_whether_inform_bid_interval"
    "- プレイヤー 1が入札額を伝えた場合、その数値はいくらか（ない場合は-1）：player1_inform_exact_self_bid"
    "- プレイヤー 2が入札額を伝えた場合, その数値はいくらか（ない場合は-1）：player2_inform_exact_self_bid"
    "- 注意：ここでの「bid」は入札価格であり、利得（payoff）ではありません。"
    "- プレイヤー 1が入札額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player1_inform_bid_interval_minbound, player1_inform_bid_interval_maxbound"
    "- プレイヤー 2が入札額の範囲を伝えた場合、その下限と上限はいくらか（ない場合は-1）：player2_inform_bid_interval_minbound, player2_inform_bid_interval_maxbound"
    "- 両者が事前に勝者を決定したか（決定していない場合は-1、どちらでも良いと決めた場合は0、プレイヤー1と決めた場合は1、プレイヤー2と決めた場合は2）：Whether_Pre_Decide_Winner"
    "- 事前に勝者を決めた際、勝者から敗者への送金（transfer）形式を以下から選択：'50% of the payoff' / 'Exact number' / 'Interval' / 'Some points (not specific)' / 'Nothing(not mentioned or no pre-decided winner)': Pre_Decide_Winner_Committed_Transfer_Format"
    "- 約束された送金の具体的な数値はいくらか（ない場合は-1）：Pre_Decide_Winner_Committed_Transfer_Number"
    "- 約束された送金額の範囲（下限と上限）はいくらか（ない場合は-1）：Pre_Decide_Winner_Committed_Transfer_interval_minbound, Pre_Decide_Winner_Committed_Transfer_interval_maxbound"
    "- 談合（共謀・Collusion）の疑いがあるか判断してください（例：事前に勝者を決める、「共謀に誓います」「協力します」といった談合を示唆する発言があるなど）。（ない場合は-1、不明な場合は0、ある場合は1）：Whether_Collusion"
)
