SystemPROMPT_T1firstnofine = (
    "I will send you a chat log between participants in an economics experiment. This experiment is a 'first price auction' conducted in pairs (Player 1 and Player 2). Both participants have their own 'value' (valuation) for the item being auctioned, which only they can see."
    "Before bidding, both parties can choose to communicate via chat. After bidding, the person with the higher bid wins the item, and their payoff is: Value - Bid. The winner also has the option to give a portion of their payoff to the loser (transfer)."
    
    "Please analyze the chat log and extract the following key information:"
    "- Whether Player 1 informed their exact self-value (a number): player1_whether_inform_exact_self_value"
    "- Whether Player 2 informed their exact self-value (a number): player2_whether_inform_exact_self_value"
    "- Whether Player 1 informed their value interval: player1_whether_inform_value_interval"
    "- Whether Player 2 informed their value interval: player2_whether_inform_value_interval"
    "- If Player 1 informed their exact self-value, what was that value (return -1 if not): player1_inform_exact_self_value"
    "- If Player 2 informed their exact self-value, what was that value (return -1 if not): player2_inform_exact_self_value"
    "- If Player 1 informed their value interval, what were the bounds (return -1 if not): player1_inform_value_interval_minbound, player1_inform_value_interval_maxbound"
    "- If Player 2 informed their value interval, what were the bounds (return -1 if not): player2_inform_value_interval_minbound, player2_inform_value_interval_maxbound"
    "- Whether Player 1 told the opponent their intended bid (a number): player1_whether_inform_exact_self_bid"
    "- Whether Player 2 told the opponent their intended bid (a number): player2_whether_inform_exact_self_bid"
    "- Whether Player 1 told the opponent their bid interval: player1_whether_inform_bid_interval"
    "- Whether Player 2 told the opponent their bid interval: player2_whether_inform_bid_interval"
    "- If Player 1 told the opponent their intended bid, what was that bid (return -1 if not): player1_inform_exact_self_bid"
    "- If Player 2 told the opponent their intended bid, what was that bid (return -1 if not): player2_inform_exact_self_bid"
    "- Note: 'bid' refers to the auction price, not the payoff (profit)."
    "- If Player 1 told their bid interval, what were the bounds (return -1 if not): player1_inform_bid_interval_minbound, player1_inform_bid_interval_maxbound"
    "- If Player 2 told their bid interval, what were the bounds (return -1 if not): player2_inform_bid_interval_minbound, player2_inform_bid_interval_maxbound"
    "- Whether the parties pre-decided a winner (return -1 if not decided, 0 if decided as 'either one', 1 if Player 1, 2 if Player 2): Whether_Pre_Decide_Winner"
    "- If a winner was pre-decided, judge the format of the committed transfer from winner to loser, return one of the following five options: '50% of the payoff' / 'Exact number' / 'Interval' / 'Some points (not specific)' / 'Nothing (not mentioned or no pre-decided winner)': Pre_Decide_Winner_Committed_Transfer_Format"
    "- What was the exact number of the committed transfer (return -1 if none): Pre_Decide_Winner_Committed_Transfer_Number"
    "- What was the interval of the committed transfer (return -1 if none): Pre_Decide_Winner_Committed_Transfer_interval_minbound, Pre_Decide_Winner_Committed_Transfer_interval_maxbound"
    "- Judge whether there was collusion (e.g., pre-deciding a winner or using symbolic phrases like 'I swear to collude' or 'Let's cooperate'). (Return -1 if none, 0 if uncertain, 1 if collusion exists): Whether_Collusion"
)

SystemPROMPT_T2firstfine0 = (
    "I will send you a chat log between participants in an economics experiment. This experiment is a 'first price auction' conducted in pairs (Player 1 and Player 2). Both participants have their own 'value' (valuation) for the item being auctioned, which only they can see."
    "Before bidding, both parties can choose to communicate via chat. After bidding, the higher bid wins; payoff is: Value - Bid. The winner can choose to give a portion of their payoff to the loser (transfer)."
    
    ############################## ############################## ############################## ############################## ############################## ############################## ############################## ##############################
    "However, if the parties communicate via chat or perform a transfer, it is considered collusion, and both may be fined 250 points. For this session, the detection probability for collusion is set to 0%."
    "Since the detection probability is 0%, the actual probability of incurring a fine is 0%."
     ############################## ############################## ############################## ############################## ############################## ############################## ############################## ##############################
    
    "Please analyze the chat log and extract the following key information:"
    "- Whether Player 1 informed their exact self-value (a number): player1_whether_inform_exact_self_value"
    "- Whether Player 2 informed their exact self-value (a number): player2_whether_inform_exact_self_value"
    "- Whether Player 1 informed their value interval: player1_whether_inform_value_interval"
    "- Whether Player 2 informed their value interval: player2_whether_inform_value_interval"
    "- If Player 1 informed their exact self-value, what was that value (return -1 if not): player1_inform_exact_self_value"
    "- If Player 2 informed their exact self-value, what was that value (return -1 if not): player2_inform_exact_self_value"
    "- If Player 1 informed their value interval, what were the bounds (return -1 if not): player1_inform_value_interval_minbound, player1_inform_value_interval_maxbound"
    "- If Player 2 informed their value interval, what were the bounds (return -1 if not): player2_inform_value_interval_minbound, player2_inform_value_interval_maxbound"
    "- Whether Player 1 told the opponent their intended bid (a number): player1_whether_inform_exact_self_bid"
    "- Whether Player 2 told the opponent their intended bid (a number): player2_whether_inform_exact_self_bid"
    "- Whether Player 1 told the opponent their bid interval: player1_whether_inform_bid_interval"
    "- Whether Player 2 told the opponent their bid interval: player2_whether_inform_bid_interval"
    "- If Player 1 told the opponent their intended bid, what was that bid (return -1 if not): player1_inform_exact_self_bid"
    "- If Player 2 told the opponent their intended bid, what was that bid (return -1 if not): player2_inform_exact_self_bid"
    "- Note: 'bid' refers to the auction price, not the payoff (profit)."
    "- If Player 1 told their bid interval, what were the bounds (return -1 if not): player1_inform_bid_interval_minbound, player1_inform_bid_interval_maxbound"
    "- If Player 2 told their bid interval, what were the bounds (return -1 if not): player2_inform_bid_interval_minbound, player2_inform_bid_interval_maxbound"
    "- Whether the parties pre-decided a winner (return -1 if not decided, 0 if decided as 'either one', 1 if Player 1, 2 if Player 2): Whether_Pre_Decide_Winner"
    "- If a winner was pre-decided, judge the format of the committed transfer from winner to loser, return one of the following five options: '50% of the payoff' / 'Exact number' / 'Interval' / 'Some points (not specific)' / 'Nothing (not mentioned or no pre-decided winner)': Pre_Decide_Winner_Committed_Transfer_Format"
    "- What was the exact number of the committed transfer (return -1 if none): Pre_Decide_Winner_Committed_Transfer_Number"
    "- What was the interval of the committed transfer (return -1 if none): Pre_Decide_Winner_Committed_Transfer_interval_minbound, Pre_Decide_Winner_Committed_Transfer_interval_maxbound"
    "- Judge whether there was collusion (e.g., pre-deciding a winner or using symbolic phrases like 'I swear to collude' or 'Let's cooperate'). (Return -1 if none, 0 if uncertain, 1 if collusion exists): Whether_Collusion"
)

SystemPROMPT_T3firstfine25 = (
    "I will send you a chat log between participants in an economics experiment. This experiment is a 'first price auction' conducted in pairs (Player 1 and Player 2). Both participants have their own 'value' (valuation) only they can see."
    "Before bidding, both parties can choose to communicate via chat. After bidding, the higher bid wins; payoff is: Value - Bid. The winner can choose to give a portion of their payoff to the loser (transfer)."
    
    ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ##########
    "[Fine Rule] If the parties communicate via chat or perform a transfer, it is considered collusion, and both may be fined 250 points. The detection probability for collusion is set to 25%."
    "- If collusion is NOT detected (75% probability): No fine is paid."
    "- If collusion IS detected (25% probability): A fine of 250 points must be paid."
     ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## 
    
    "Please analyze the chat log and extract the following key information:"
    "- Whether Player 1 informed their exact self-value (a number): player1_whether_inform_exact_self_value"
    "- Whether Player 2 informed their exact self-value (a number): player2_whether_inform_exact_self_value"
    "- Whether Player 1 informed their value interval: player1_whether_inform_value_interval"
    "- Whether Player 2 informed their value interval: player2_whether_inform_value_interval"
    "- If Player 1 informed their exact self-value, what was that value (return -1 if not): player1_inform_exact_self_value"
    "- If Player 2 informed their exact self-value, what was that value (return -1 if not): player2_inform_exact_self_value"
    "- If Player 1 informed their value interval, what were the bounds (return -1 if not): player1_inform_value_interval_minbound, player1_inform_value_interval_maxbound"
    "- If Player 2 informed their value interval, what were the bounds (return -1 if not): player2_inform_value_interval_minbound, player2_inform_value_interval_maxbound"
    "- Whether Player 1 told the opponent their intended bid (a number): player1_whether_inform_exact_self_bid"
    "- Whether Player 2 told the opponent their intended bid (a number): player2_whether_inform_exact_self_bid"
    "- Whether Player 1 told the opponent their bid interval: player1_whether_inform_bid_interval"
    "- Whether Player 2 told the opponent their bid interval: player2_whether_inform_bid_interval"
    "- If Player 1 told the opponent their intended bid, what was that bid (return -1 if not): player1_inform_exact_self_bid"
    "- If Player 2 told the opponent their intended bid, what was that bid (return -1 if not): player2_inform_exact_self_bid"
    "- Note: 'bid' refers to the auction price, not the payoff (profit)."
    "- If Player 1 told their bid interval, what were the bounds (return -1 if not): player1_inform_bid_interval_minbound, player1_inform_bid_interval_maxbound"
    "- If Player 2 told their bid interval, what were the bounds (return -1 if not): player2_inform_bid_interval_minbound, player2_inform_bid_interval_maxbound"
    "- Whether the parties pre-decided a winner (return -1 if not decided, 0 if decided as 'either one', 1 if Player 1, 2 if Player 2): Whether_Pre_Decide_Winner"
    "- If a winner was pre-decided, judge the format of the committed transfer from winner to loser, return one of the following five options: '50% of the payoff' / 'Exact number' / 'Interval' / 'Some points (not specific)' / 'Nothing (not mentioned or no pre-decided winner)': Pre_Decide_Winner_Committed_Transfer_Format"
    "- What was the exact number of the committed transfer (return -1 if none): Pre_Decide_Winner_Committed_Transfer_Number"
    "- What was the interval of the committed transfer (return -1 if none): Pre_Decide_Winner_Committed_Transfer_interval_minbound, Pre_Decide_Winner_Committed_Transfer_interval_maxbound"
    "- Judge whether there was collusion (e.g., pre-deciding a winner or using symbolic phrases like 'I swear to collude' or 'Let's cooperate'). (Return -1 if none, 0 if uncertain, 1 if collusion exists): Whether_Collusion"
)

SystemPROMPT_T4secondnofine = (
    "I will send you a chat log between participants in an economics experiment. This experiment is a 'second price auction' conducted in pairs (Player 1 and Player 2). Both participants have their own 'value' (valuation) for the item being auctioned, which only they can see."
    "Before bidding, both parties can choose to communicate via chat. After bidding, the person with the higher bid wins the item, and their payoff is: Value - Second Highest Bid (the loser's bid). The winner also has the option to give a portion of their payoff to the loser (transfer)."


    "Please analyze the chat log and extract the following key information:"
    "- Whether Player 1 informed their exact self-value (a number): player1_whether_inform_exact_self_value"
    "- Whether Player 2 informed their exact self-value (a number): player2_whether_inform_exact_self_value"
    "- Whether Player 1 informed their value interval: player1_whether_inform_value_interval"
    "- Whether Player 2 informed their value interval: player2_whether_inform_value_interval"
    "- If Player 1 informed their exact self-value, what was that value (return -1 if not): player1_inform_exact_self_value"
    "- If Player 2 informed their exact self-value, what was that value (return -1 if not): player2_inform_exact_self_value"
    "- If Player 1 informed their value interval, what were the bounds (return -1 if not): player1_inform_value_interval_minbound, player1_inform_value_interval_maxbound"
    "- If Player 2 informed their value interval, what were the bounds (return -1 if not): player2_inform_value_interval_minbound, player2_inform_value_interval_maxbound"
    "- Whether Player 1 told the opponent their intended bid (a number): player1_whether_inform_exact_self_bid"
    "- Whether Player 2 told the opponent their intended bid (a number): player2_whether_inform_exact_self_bid"
    "- Whether Player 1 told the opponent their bid interval: player1_whether_inform_bid_interval"
    "- Whether Player 2 told the opponent their bid interval: player2_whether_inform_bid_interval"
    "- If Player 1 told the opponent their intended bid, what was that bid (return -1 if not): player1_inform_exact_self_bid"
    "- If Player 2 told the opponent their intended bid, what was that bid (return -1 if not): player2_inform_exact_self_bid"
    "- Note: 'bid' refers to the auction price, not the payoff (profit)."
    "- If Player 1 told their bid interval, what were the bounds (return -1 if not): player1_inform_bid_interval_minbound, player1_inform_bid_interval_maxbound"
    "- If Player 2 told their bid interval, what were the bounds (return -1 if not): player2_inform_bid_interval_minbound, player2_inform_bid_interval_maxbound"
    "- Whether the parties pre-decided a winner (return -1 if not decided, 0 if decided as 'either one', 1 if Player 1, 2 if Player 2): Whether_Pre_Decide_Winner"
    "- If a winner was pre-decided, judge the format of the committed transfer from winner to loser, return one of the following five options: '50% of the payoff' / 'Exact number' / 'Interval' / 'Some points (not specific)' / 'Nothing (not mentioned or no pre-decided winner)': Pre_Decide_Winner_Committed_Transfer_Format"
    "- What was the exact number of the committed transfer (return -1 if none): Pre_Decide_Winner_Committed_Transfer_Number"
    "- What was the interval of the committed transfer (return -1 if none): Pre_Decide_Winner_Committed_Transfer_interval_minbound, Pre_Decide_Winner_Committed_Transfer_interval_maxbound"
    "- Judge whether there was collusion (e.g., pre-deciding a winner or using symbolic phrases like 'I swear to collude' or 'Let's cooperate'). (Return -1 if none, 0 if uncertain, 1 if collusion exists): Whether_Collusion"
)

SystemPROMPT_T5secondfine0 = (
    "I will send you a chat log between participants in an economics experiment. This experiment is a 'second price auction' conducted in pairs (Player 1 and Player 2). Both participants have their own 'value' (valuation) only they can see."
    "Before bidding, both parties can choose to communicate via chat. After bidding, the person with the higher bid wins; payoff is: Value - Second Highest Bid (the loser's bid). The winner can choose to give a portion of their payoff to the loser (transfer)."
    
    ############################# ############################## ############################## ############################## ############################## ############################## ############################## ##############################
    "However, if the parties communicate via chat or perform a transfer, it is considered collusion, and both may be fined 250 points. For this session, the detection probability for collusion is set to 0%."
    "Since the detection probability is 0%, the actual probability of incurring a fine is 0%."
     ############################## ############################## ############################## ############################## ############################## ############################## ############################## ##############################
    
    "Please analyze the chat log and extract the following key information:"
    "- Whether Player 1 informed their exact self-value (a number): player1_whether_inform_exact_self_value"
    "- Whether Player 2 informed their exact self-value (a number): player2_whether_inform_exact_self_value"
    "- Whether Player 1 informed their value interval: player1_whether_inform_value_interval"
    "- Whether Player 2 informed their value interval: player2_whether_inform_value_interval"
    "- If Player 1 informed their exact self-value, what was that value (return -1 if not): player1_inform_exact_self_value"
    "- If Player 2 informed their exact self-value, what was that value (return -1 if not): player2_inform_exact_self_value"
    "- If Player 1 informed their value interval, what were the bounds (return -1 if not): player1_inform_value_interval_minbound, player1_inform_value_interval_maxbound"
    "- If Player 2 informed their value interval, what were the bounds (return -1 if not): player2_inform_value_interval_minbound, player2_inform_value_interval_maxbound"
    "- Whether Player 1 told the opponent their intended bid (a number): player1_whether_inform_exact_self_bid"
    "- Whether Player 2 told the opponent their intended bid (a number): player2_whether_inform_exact_self_bid"
    "- Whether Player 1 told the opponent their bid interval: player1_whether_inform_bid_interval"
    "- Whether Player 2 told the opponent their bid interval: player2_whether_inform_bid_interval"
    "- If Player 1 told the opponent their intended bid, what was that bid (return -1 if not): player1_inform_exact_self_bid"
    "- If Player 2 told the opponent their intended bid, what was that bid (return -1 if not): player2_inform_exact_self_bid"
    "- Note: 'bid' refers to the auction price, not the payoff (profit)."
    "- If Player 1 told their bid interval, what were the bounds (return -1 if not): player1_inform_bid_interval_minbound, player1_inform_bid_interval_maxbound"
    "- If Player 2 told their bid interval, what were the bounds (return -1 if not): player2_inform_bid_interval_minbound, player2_inform_bid_interval_maxbound"
    "- Whether the parties pre-decided a winner (return -1 if not decided, 0 if decided as 'either one', 1 if Player 1, 2 if Player 2): Whether_Pre_Decide_Winner"
    "- If a winner was pre-decided, judge the format of the committed transfer from winner to loser, return one of the following five options: '50% of the payoff' / 'Exact number' / 'Interval' / 'Some points (not specific)' / 'Nothing (not mentioned or no pre-decided winner)': Pre_Decide_Winner_Committed_Transfer_Format"
    "- What was the exact number of the committed transfer (return -1 if none): Pre_Decide_Winner_Committed_Transfer_Number"
    "- What was the interval of the committed transfer (return -1 if none): Pre_Decide_Winner_Committed_Transfer_interval_minbound, Pre_Decide_Winner_Committed_Transfer_interval_maxbound"
    "- Judge whether there was collusion (e.g., pre-deciding a winner or using symbolic phrases like 'I swear to collude' or 'Let's cooperate'). (Return -1 if none, 0 if uncertain, 1 if collusion exists): Whether_Collusion"
)

SystemPROMPT_T6secondfine25 = (
    "I will send you a chat log between participants in an economics experiment. This experiment is a 'second price auction' conducted in pairs (Player 1 and Player 2). Both participants have their own 'value' (valuation) only they can see."
    "Before bidding, both parties can choose to communicate via chat. After bidding, the person with the higher bid wins; payoff is: Value - Second Highest Bid (the loser's bid). The winner can choose to give a portion of their payoff to the loser (transfer)."
########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ##########
    "[Fine Rule] If the parties communicate via chat or perform a transfer, it is considered collusion, and both may be fined 250 points. The detection probability for collusion is set to 25%."
    "- If collusion is NOT detected (75% probability): No fine is paid."
    "- If collusion IS detected (25% probability): A fine of 250 points must be paid."
     ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## ########## 
    
    "Please analyze the chat log and extract the following key information:"
    "- Whether Player 1 informed their exact self-value (a number): player1_whether_inform_exact_self_value"
    "- Whether Player 2 informed their exact self-value (a number): player2_whether_inform_exact_self_value"
    "- Whether Player 1 informed their value interval: player1_whether_inform_value_interval"
    "- Whether Player 2 informed their value interval: player2_whether_inform_value_interval"
    "- If Player 1 informed their exact self-value, what was that value (return -1 if not): player1_inform_exact_self_value"
    "- If Player 2 informed their exact self-value, what was that value (return -1 if not): player2_inform_exact_self_value"
    "- If Player 1 informed their value interval, what were the bounds (return -1 if not): player1_inform_value_interval_minbound, player1_inform_value_interval_maxbound"
    "- If Player 2 informed their value interval, what were the bounds (return -1 if not): player2_inform_value_interval_minbound, player2_inform_value_interval_maxbound"
    "- Whether Player 1 told the opponent their intended bid (a number): player1_whether_inform_exact_self_bid"
    "- Whether Player 2 told the opponent their intended bid (a number): player2_whether_inform_exact_self_bid"
    "- Whether Player 1 told the opponent their bid interval: player1_whether_inform_bid_interval"
    "- Whether Player 2 told the opponent their bid interval: player2_whether_inform_bid_interval"
    "- If Player 1 told the opponent their intended bid, what was that bid (return -1 if not): player1_inform_exact_self_bid"
    "- If Player 2 told the opponent their intended bid, what was that bid (return -1 if not): player2_inform_exact_self_bid"
    "- Note: 'bid' refers to the auction price, not the payoff (profit)."
    "- If Player 1 told their bid interval, what were the bounds (return -1 if not): player1_inform_bid_interval_minbound, player1_inform_bid_interval_maxbound"
    "- If Player 2 told their bid interval, what were the bounds (return -1 if not): player2_inform_bid_interval_minbound, player2_inform_bid_interval_maxbound"
    "- Whether the parties pre-decided a winner (return -1 if not decided, 0 if decided as 'either one', 1 if Player 1, 2 if Player 2): Whether_Pre_Decide_Winner"
    "- If a winner was pre-decided, judge the format of the committed transfer from winner to loser, return one of the following five options: '50% of the payoff' / 'Exact number' / 'Interval' / 'Some points (not specific)' / 'Nothing (not mentioned or no pre-decided winner)': Pre_Decide_Winner_Committed_Transfer_Format"
    "- What was the exact number of the committed transfer (return -1 if none): Pre_Decide_Winner_Committed_Transfer_Number"
    "- What was the interval of the committed transfer (return -1 if none): Pre_Decide_Winner_Committed_Transfer_interval_minbound, Pre_Decide_Winner_Committed_Transfer_interval_maxbound"
    "- Judge whether there was collusion (e.g., pre-deciding a winner or using symbolic phrases like 'I swear to collude' or 'Let's cooperate'). (Return -1 if none, 0 if uncertain, 1 if collusion exists): Whether_Collusion"
)